version: "3.8"

services:
  openrefine:
    image: openrefine/openrefine:latest
    ports:
      - "3333:3333"
    volumes:
      - openrefine-data:/data
    command: >
      /app/refine
      -i 0.0.0.0
      -p 3333
      -d /data

volumes:
  openrefine-data:
